name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build using maven
        run: mvn -B verify --file pom.xml

#      - name: Deploy to Remote Server
#        uses: appleboy/ssh-action@main
#        with:
#          host: ${{ secrets.SSH_HOST }}
#          port: ${{ secrets.SSH_PORT }}
#          username: ${{ secrets.SSH_USERNAME }}
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          script: |
#            cd /var/www/bpm-calculator
#            git pull origin main
#            poetry install --no-root
#            systemctl restart bpm-calculator-flask.service