name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B package --file pom.xml

#      - name: Deploy to Remote Server
#        uses: appleboy/ssh-action@main
#        with:
#          host: ${{ secrets.SSH_HOST }}
#          port: ${{ secrets.SSH_PORT }}
#          username: ${{ secrets.SSH_USERNAME }}
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          script: |
#            cd /var/www/bpm-calculator
#            git pull origin main
#            poetry install --no-root
#            systemctl restart bpm-calculator-flask.service