name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Deploy to Remote Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "target/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: "/bpm-calculator-0.0.1-SNAPSHOT/, /classes/, /generated-sources/, /generated-test-sources/, /maven-archiver/, /maven-status/, /surefire-reports/, /test-classes/"
          SCRIPT_BEFORE: |
            whoami
            cd ${{ secrets.REMOTE_TEMP_DIR }} && rm -rf *
          SCRIPT_AFTER: |
            echo $RSYNC_STDOUT
            mv ${{ secrets.REMOTE_TEMP_DIR }}/bpm.war ${{ secrets.REMOTE_TARGET }}
            tomcat stop 1 && tomcat start
          SCRIPT_AFTER_REQUIRED: true